if failed file exists exit with error code

diff --git a/build/playbooks/templates/do-tests.sh.j2 b/build/playbooks/templates/do-tests.sh.j2
--- a/build/playbooks/templates/do-tests.sh.j2
+++ b/build/playbooks/templates/do-tests.sh.j2
@@ -25,6 +25,10 @@ cd {{ bw_project_base_dir }}
 {% for item in selected_suite %}
 {% for selected_file in test_file if selected_file.suite == item %}
 /usr/local/bin/codecept run acceptance {{ selected_file.testsuite_file }} -vvv --xml xmlreports/report_{{ item }}.xml --html htmlreports/report_{{ item }}.html
+if [ -f {{ test_log_path }}/failed ]; then
+  echo "Current test {{ item }} failed!"
+  exit 1
+fi
 {% endfor %}
 {% endfor %}
 {% endfor %}
